export type Provincia = { code: string; name: string };

// ==================== ESPAÑA (INE) ====================
export const PROVINCIAS_INE: readonly Provincia[] = [
  { code: '01', name: 'Araba/Álava' },
  { code: '02', name: 'Albacete' },
  { code: '03', name: 'Alicante/Alacant' },
  { code: '04', name: 'Almería' },
  { code: '05', name: 'Ávila' },
  { code: '06', name: 'Badajoz' },
  { code: '07', name: 'Illes Balears' },
  { code: '08', name: 'Barcelona' },
  { code: '09', name: 'Burgos' },
  { code: '10', name: 'Cáceres' },
  { code: '11', name: 'Cádiz' },
  { code: '12', name: 'Castellón/Castelló' },
  { code: '13', name: 'Ciudad Real' },
  { code: '14', name: 'Córdoba' },
  { code: '15', name: 'A Coruña' },
  { code: '16', name: 'Cuenca' },
  { code: '17', name: 'Girona' },
  { code: '18', name: 'Granada' },
  { code: '19', name: 'Guadalajara' },
  { code: '20', name: 'Gipuzkoa' },
  { code: '21', name: 'Huelva' },
  { code: '22', name: 'Huesca' },
  { code: '23', name: 'Jaén' },
  { code: '24', name: 'León' },
  { code: '25', name: 'Lleida' },
  { code: '26', name: 'La Rioja' },
  { code: '27', name: 'Lugo' },
  { code: '28', name: 'Madrid' },
  { code: '29', name: 'Málaga' },
  { code: '30', name: 'Murcia' },
  { code: '31', name: 'Navarra' },
  { code: '32', name: 'Ourense' },
  { code: '33', name: 'Asturias' },
  { code: '34', name: 'Palencia' },
  { code: '35', name: 'Las Palmas' },
  { code: '36', name: 'Pontevedra' },
  { code: '37', name: 'Salamanca' },
  { code: '38', name: 'Santa Cruz de Tenerife' },
  { code: '39', name: 'Cantabria' },
  { code: '40', name: 'Segovia' },
  { code: '41', name: 'Sevilla' },
  { code: '42', name: 'Soria' },
  { code: '43', name: 'Tarragona' },
  { code: '44', name: 'Teruel' },
  { code: '45', name: 'Toledo' },
  { code: '46', name: 'Valencia/València' },
  { code: '47', name: 'Valladolid' },
  { code: '48', name: 'Bizkaia' },
  { code: '49', name: 'Zamora' },
  { code: '50', name: 'Zaragoza' },
  { code: '51', name: 'Ceuta' },
  { code: '52', name: 'Melilla' },
] as const;

// ==================== MÉXICO (INEGI) ====================
export const ENTIDADES_MX_INEGI: readonly Provincia[] = [
  { code: '01', name: 'Aguascalientes' },
  { code: '02', name: 'Baja California' },
  { code: '03', name: 'Baja California Sur' },
  { code: '04', name: 'Campeche' },
  { code: '05', name: 'Coahuila de Zaragoza' },
  { code: '06', name: 'Colima' },
  { code: '07', name: 'Chiapas' },
  { code: '08', name: 'Chihuahua' },
  { code: '09', name: 'Ciudad de México' },
  { code: '10', name: 'Durango' },
  { code: '11', name: 'Guanajuato' },
  { code: '12', name: 'Guerrero' },
  { code: '13', name: 'Hidalgo' },
  { code: '14', name: 'Jalisco' },
  { code: '15', name: 'México' },
  { code: '16', name: 'Michoacán de Ocampo' },
  { code: '17', name: 'Morelos' },
  { code: '18', name: 'Nayarit' },
  { code: '19', name: 'Nuevo León' },
  { code: '20', name: 'Oaxaca' },
  { code: '21', name: 'Puebla' },
  { code: '22', name: 'Querétaro' },
  { code: '23', name: 'Quintana Roo' },
  { code: '24', name: 'San Luis Potosí' },
  { code: '25', name: 'Sinaloa' },
  { code: '26', name: 'Sonora' },
  { code: '27', name: 'Tabasco' },
  { code: '28', name: 'Tamaulipas' },
  { code: '29', name: 'Tlaxcala' },
  { code: '30', name: 'Veracruz de Ignacio de la Llave' },
  { code: '31', name: 'Yucatán' },
  { code: '32', name: 'Zacatecas' },
] as const;

// ==================== ARGENTINA (AR) ====================
export const PROVINCIAS_AR: readonly Provincia[] = [
  { code: '01', name: 'Buenos Aires' },
  { code: '02', name: 'Ciudad Autónoma de Buenos Aires' },
  { code: '03', name: 'Catamarca' },
  { code: '04', name: 'Chaco' },
  { code: '05', name: 'Chubut' },
  { code: '06', name: 'Córdoba' },
  { code: '07', name: 'Corrientes' },
  { code: '08', name: 'Entre Ríos' },
  { code: '09', name: 'Formosa' },
  { code: '10', name: 'Jujuy' },
  { code: '11', name: 'La Pampa' },
  { code: '12', name: 'La Rioja' },
  { code: '13', name: 'Mendoza' },
  { code: '14', name: 'Misiones' },
  { code: '15', name: 'Neuquén' },
  { code: '16', name: 'Río Negro' },
  { code: '17', name: 'Salta' },
  { code: '18', name: 'San Juan' },
  { code: '19', name: 'San Luis' },
  { code: '20', name: 'Santa Cruz' },
  { code: '21', name: 'Santa Fe' },
  { code: '22', name: 'Santiago del Estero' },
  { code: '23', name: 'Tierra del Fuego, Antártida e Islas del Atlántico Sur' },
  { code: '24', name: 'Tucumán' },
] as const;

// ==================== BOLIVIA (BO) ====================
export const DEPARTAMENTOS_BO: readonly Provincia[] = [
  { code: '01', name: 'Beni' },
  { code: '02', name: 'Chuquisaca' },
  { code: '03', name: 'Cochabamba' },
  { code: '04', name: 'La Paz' },
  { code: '05', name: 'Oruro' },
  { code: '06', name: 'Pando' },
  { code: '07', name: 'Potosí' },
  { code: '08', name: 'Santa Cruz' },
  { code: '09', name: 'Tarija' },
] as const;

// ==================== CHILE (CL) ====================
export const REGIONES_CL: readonly Provincia[] = [
  { code: '01', name: 'Arica y Parinacota' },
  { code: '02', name: 'Tarapacá' },
  { code: '03', name: 'Antofagasta' },
  { code: '04', name: 'Atacama' },
  { code: '05', name: 'Coquimbo' },
  { code: '06', name: 'Valparaíso' },
  { code: '07', name: 'Región Metropolitana de Santiago' },
  { code: '08', name: "Libertador General Bernardo O'Higgins" },
  { code: '09', name: 'Maule' },
  { code: '10', name: 'Ñuble' },
  { code: '11', name: 'Biobío' },
  { code: '12', name: 'La Araucanía' },
  { code: '13', name: 'Los Ríos' },
  { code: '14', name: 'Los Lagos' },
  { code: '15', name: 'Aysén del General Carlos Ibáñez del Campo' },
  { code: '16', name: 'Magallanes y de la Antártica Chilena' },
] as const;

// ==================== COLOMBIA (CO) ====================
export const DEPARTAMENTOS_CO: readonly Provincia[] = [
  { code: '01', name: 'Amazonas' },
  { code: '02', name: 'Antioquia' },
  { code: '03', name: 'Arauca' },
  { code: '04', name: 'Atlántico' },
  { code: '05', name: 'Bogotá, D.C.' },
  { code: '06', name: 'Bolívar' },
  { code: '07', name: 'Boyacá' },
  { code: '08', name: 'Caldas' },
  { code: '09', name: 'Caquetá' },
  { code: '10', name: 'Casanare' },
  { code: '11', name: 'Cauca' },
  { code: '12', name: 'Cesar' },
  { code: '13', name: 'Chocó' },
  { code: '14', name: 'Córdoba' },
  { code: '15', name: 'Cundinamarca' },
  { code: '16', name: 'Guainía' },
  { code: '17', name: 'Guaviare' },
  { code: '18', name: 'Huila' },
  { code: '19', name: 'La Guajira' },
  { code: '20', name: 'Magdalena' },
  { code: '21', name: 'Meta' },
  { code: '22', name: 'Nariño' },
  { code: '23', name: 'Norte de Santander' },
  { code: '24', name: 'Putumayo' },
  { code: '25', name: 'Quindío' },
  { code: '26', name: 'Risaralda' },
  { code: '27', name: 'San Andrés y Providencia' },
  { code: '28', name: 'Santander' },
  { code: '29', name: 'Sucre' },
  { code: '30', name: 'Tolima' },
  { code: '31', name: 'Valle del Cauca' },
  { code: '32', name: 'Vaupés' },
  { code: '33', name: 'Vichada' },
] as const;

// ==================== COSTA RICA (CR) ====================
export const PROVINCIAS_CR: readonly Provincia[] = [
  { code: '01', name: 'San José' },
  { code: '02', name: 'Alajuela' },
  { code: '03', name: 'Cartago' },
  { code: '04', name: 'Heredia' },
  { code: '05', name: 'Guanacaste' },
  { code: '06', name: 'Puntarenas' },
  { code: '07', name: 'Limón' },
] as const;

// ==================== CUBA (CU) ====================
export const PROVINCIAS_CU: readonly Provincia[] = [
  { code: '01', name: 'Pinar del Río' },
  { code: '02', name: 'Artemisa' },
  { code: '03', name: 'La Habana' },
  { code: '04', name: 'Mayabeque' },
  { code: '05', name: 'Matanzas' },
  { code: '06', name: 'Cienfuegos' },
  { code: '07', name: 'Villa Clara' },
  { code: '08', name: 'Sancti Spíritus' },
  { code: '09', name: 'Ciego de Ávila' },
  { code: '10', name: 'Camagüey' },
  { code: '11', name: 'Las Tunas' },
  { code: '12', name: 'Holguín' },
  { code: '13', name: 'Granma' },
  { code: '14', name: 'Santiago de Cuba' },
  { code: '15', name: 'Guantánamo' },
  { code: '16', name: 'Isla de la Juventud' },
] as const;

// ==================== REPÚBLICA DOMINICANA (DO) ====================
export const PROVINCIAS_DO: readonly Provincia[] = [
  { code: '01', name: 'Distrito Nacional' },
  { code: '02', name: 'La Altagracia' },
  { code: '03', name: 'Azua' },
  { code: '04', name: 'Bahoruco' },
  { code: '05', name: 'Barahona' },
  { code: '06', name: 'Dajabón' },
  { code: '07', name: 'Duarte' },
  { code: '08', name: 'El Seibo' },
  { code: '09', name: 'Elías Piña' },
  { code: '10', name: 'Espaillat' },
  { code: '11', name: 'Hato Mayor' },
  { code: '12', name: 'Independencia' },
  { code: '13', name: 'La Romana' },
  { code: '14', name: 'La Vega' },
  { code: '15', name: 'María Trinidad Sánchez' },
  { code: '16', name: 'Monseñor Nouel' },
  { code: '17', name: 'Montecristi' },
  { code: '18', name: 'Monte Plata' },
  { code: '19', name: 'Pedernales' },
  { code: '20', name: 'Peravia' },
  { code: '21', name: 'Puerto Plata' },
  { code: '22', name: 'Hermanas Mirabal' },
  { code: '23', name: 'Samaná' },
  { code: '24', name: 'San Cristóbal' },
  { code: '25', name: 'San Juan' },
  { code: '26', name: 'San Pedro de Macorís' },
  { code: '27', name: 'Sánchez Ramírez' },
  { code: '28', name: 'Santiago' },
  { code: '29', name: 'Santiago Rodríguez' },
  { code: '30', name: 'Valverde' },
  { code: '31', name: 'San José de Ocoa' },
  { code: '32', name: 'Santo Domingo' },
] as const;

// ==================== ECUADOR (EC) ====================
export const PROVINCIAS_EC: readonly Provincia[] = [
  { code: '01', name: 'Azuay' },
  { code: '02', name: 'Bolívar' },
  { code: '03', name: 'Cañar' },
  { code: '04', name: 'Carchi' },
  { code: '05', name: 'Chimborazo' },
  { code: '06', name: 'Cotopaxi' },
  { code: '07', name: 'El Oro' },
  { code: '08', name: 'Esmeraldas' },
  { code: '09', name: 'Galápagos' },
  { code: '10', name: 'Guayas' },
  { code: '11', name: 'Imbabura' },
  { code: '12', name: 'Loja' },
  { code: '13', name: 'Los Ríos' },
  { code: '14', name: 'Manabí' },
  { code: '15', name: 'Morona Santiago' },
  { code: '16', name: 'Napo' },
  { code: '17', name: 'Orellana' },
  { code: '18', name: 'Pastaza' },
  { code: '19', name: 'Pichincha' },
  { code: '20', name: 'Santa Elena' },
  { code: '21', name: 'Santo Domingo de los Tsáchilas' },
  { code: '22', name: 'Sucumbíos' },
  { code: '23', name: 'Tungurahua' },
  { code: '24', name: 'Zamora Chinchipe' },
] as const;

// ==================== GUATEMALA (GT) ====================
export const DEPARTAMENTOS_GT: readonly Provincia[] = [
  { code: '01', name: 'Alta Verapaz' },
  { code: '02', name: 'Baja Verapaz' },
  { code: '03', name: 'Chimaltenango' },
  { code: '04', name: 'Chiquimula' },
  { code: '05', name: 'El Progreso' },
  { code: '06', name: 'Escuintla' },
  { code: '07', name: 'Guatemala' },
  { code: '08', name: 'Huehuetenango' },
  { code: '09', name: 'Izabal' },
  { code: '10', name: 'Jalapa' },
  { code: '11', name: 'Jutiapa' },
  { code: '12', name: 'Petén' },
  { code: '13', name: 'Quetzaltenango' },
  { code: '14', name: 'Quiché' },
  { code: '15', name: 'Retalhuleu' },
  { code: '16', name: 'Sacatepéquez' },
  { code: '17', name: 'San Marcos' },
  { code: '18', name: 'Santa Rosa' },
  { code: '19', name: 'Sololá' },
  { code: '20', name: 'Suchitepéquez' },
  { code: '21', name: 'Totonicapán' },
  { code: '22', name: 'Zacapa' },
] as const;

// ==================== HONDURAS (HN) ====================
export const DEPARTAMENTOS_HN: readonly Provincia[] = [
  { code: '01', name: 'Atlántida' },
  { code: '02', name: 'Choluteca' },
  { code: '03', name: 'Colón' },
  { code: '04', name: 'Comayagua' },
  { code: '05', name: 'Copán' },
  { code: '06', name: 'Cortés' },
  { code: '07', name: 'El Paraíso' },
  { code: '08', name: 'Francisco Morazán' },
  { code: '09', name: 'Gracias a Dios' },
  { code: '10', name: 'Intibucá' },
  { code: '11', name: 'Islas de la Bahía' },
  { code: '12', name: 'La Paz' },
  { code: '13', name: 'Lempira' },
  { code: '14', name: 'Ocotepeque' },
  { code: '15', name: 'Olancho' },
  { code: '16', name: 'Santa Bárbara' },
  { code: '17', name: 'Valle' },
  { code: '18', name: 'Yoro' },
] as const;

// ==================== NICARAGUA (NI) ====================
export const DEPARTAMENTOS_NI: readonly Provincia[] = [
  { code: '01', name: 'Boaco' },
  { code: '02', name: 'Carazo' },
  { code: '03', name: 'Chinandega' },
  { code: '04', name: 'Chontales' },
  { code: '05', name: 'Estelí' },
  { code: '06', name: 'Granada' },
  { code: '07', name: 'Jinotega' },
  { code: '08', name: 'León' },
  { code: '09', name: 'Madriz' },
  { code: '10', name: 'Managua' },
  { code: '11', name: 'Masaya' },
  { code: '12', name: 'Matagalpa' },
  { code: '13', name: 'Nueva Segovia' },
  { code: '14', name: 'Río San Juan' },
  { code: '15', name: 'Rivas' },
  { code: '16', name: 'Costa Caribe Norte' },
  { code: '17', name: 'Costa Caribe Sur' },
] as const;

// ==================== PANAMÁ (PA) ====================
export const PROVINCIAS_PA: readonly Provincia[] = [
  // Provincias
  { code: '01', name: 'Bocas del Toro' },
  { code: '02', name: 'Coclé' },
  { code: '03', name: 'Colón' },
  { code: '04', name: 'Chiriquí' },
  { code: '05', name: 'Darién' },
  { code: '06', name: 'Herrera' },
  { code: '07', name: 'Los Santos' },
  { code: '08', name: 'Panamá' },
  { code: '09', name: 'Veraguas' },
  { code: '10', name: 'Panamá Oeste' },
  { code: '11', name: 'Guna Yala' },
  { code: '12', name: 'Emberá-Wounaan' },
  { code: '13', name: 'Ngäbe-Buglé' },
  { code: '14', name: 'Naso Tjër Di' },
] as const;

// ==================== PERÚ (PE) ====================
export const DEPARTAMENTOS_PE: readonly Provincia[] = [
  { code: '01', name: 'Amazonas' },
  { code: '02', name: 'Áncash' },
  { code: '03', name: 'Apurímac' },
  { code: '04', name: 'Arequipa' },
  { code: '05', name: 'Ayacucho' },
  { code: '06', name: 'Cajamarca' },
  { code: '07', name: 'Callao' },
  { code: '08', name: 'Cusco' },
  { code: '09', name: 'Huancavelica' },
  { code: '10', name: 'Huánuco' },
  { code: '11', name: 'Ica' },
  { code: '12', name: 'Junín' },
  { code: '13', name: 'La Libertad' },
  { code: '14', name: 'Lambayeque' },
  { code: '15', name: 'Lima' },
  { code: '16', name: 'Loreto' },
  { code: '17', name: 'Madre de Dios' },
  { code: '18', name: 'Moquegua' },
  { code: '19', name: 'Pasco' },
  { code: '20', name: 'Piura' },
  { code: '21', name: 'Puno' },
  { code: '22', name: 'San Martín' },
  { code: '23', name: 'Tacna' },
  { code: '24', name: 'Tumbes' },
  { code: '25', name: 'Ucayali' },
] as const;

// ==================== PARAGUAY (PY) ====================
export const DEPARTAMENTOS_PY: readonly Provincia[] = [
  { code: '01', name: 'Concepción' },
  { code: '02', name: 'San Pedro' },
  { code: '03', name: 'Cordillera' },
  { code: '04', name: 'Guairá' },
  { code: '05', name: 'Caaguazú' },
  { code: '06', name: 'Caazapá' },
  { code: '07', name: 'Itapúa' },
  { code: '08', name: 'Misiones' },
  { code: '09', name: 'Paraguarí' },
  { code: '10', name: 'Alto Paraná' },
  { code: '11', name: 'Central' },
  { code: '12', name: 'Ñeembucú' },
  { code: '13', name: 'Amambay' },
  { code: '14', name: 'Canindeyú' },
  { code: '15', name: 'Presidente Hayes' },
  { code: '16', name: 'Boquerón' },
  { code: '17', name: 'Alto Paraguay' },
  { code: '18', name: 'Asunción (Distrito Capital)' },
] as const;

// ==================== EL SALVADOR (SV) ====================
export const DEPARTAMENTOS_SV: readonly Provincia[] = [
  { code: '01', name: 'Ahuachapán' },
  { code: '02', name: 'Sonsonate' },
  { code: '03', name: 'Santa Ana' },
  { code: '04', name: 'La Libertad' },
  { code: '05', name: 'Chalatenango' },
  { code: '06', name: 'San Salvador' },
  { code: '07', name: 'Cuscatlán' },
  { code: '08', name: 'La Paz' },
  { code: '09', name: 'San Vicente' },
  { code: '10', name: 'Cabañas' },
  { code: '11', name: 'Usulután' },
  { code: '12', name: 'San Miguel' },
  { code: '13', name: 'Morazán' },
  { code: '14', name: 'La Unión' },
] as const;

// ==================== URUGUAY (UY) ====================
export const DEPARTAMENTOS_UY: readonly Provincia[] = [
  { code: '01', name: 'Montevideo' },
  { code: '02', name: 'Artigas' },
  { code: '03', name: 'Canelones' },
  { code: '04', name: 'Cerro Largo' },
  { code: '05', name: 'Colonia' },
  { code: '06', name: 'Durazno' },
  { code: '07', name: 'Flores' },
  { code: '08', name: 'Florida' },
  { code: '09', name: 'Lavalleja' },
  { code: '10', name: 'Maldonado' },
  { code: '11', name: 'Paysandú' },
  { code: '12', name: 'Río Negro' },
  { code: '13', name: 'Rivera' },
  { code: '14', name: 'Rocha' },
  { code: '15', name: 'Salto' },
  { code: '16', name: 'San José' },
  { code: '17', name: 'Soriano' },
  { code: '18', name: 'Tacuarembó' },
  { code: '19', name: 'Treinta y Tres' },
] as const;

// ==================== VENEZUELA (VE) ====================
export const ESTADOS_VE: readonly Provincia[] = [
  { code: '01', name: 'Amazonas' },
  { code: '02', name: 'Anzoátegui' },
  { code: '03', name: 'Apure' },
  { code: '04', name: 'Aragua' },
  { code: '05', name: 'Barinas' },
  { code: '06', name: 'Bolívar' },
  { code: '07', name: 'Carabobo' },
  { code: '08', name: 'Cojedes' },
  { code: '09', name: 'Delta Amacuro' },
  { code: '10', name: 'Falcón' },
  { code: '11', name: 'Guárico' },
  { code: '12', name: 'Lara' },
  { code: '13', name: 'Mérida' },
  { code: '14', name: 'Miranda' },
  { code: '15', name: 'Monagas' },
  { code: '16', name: 'Nueva Esparta' },
  { code: '17', name: 'Portuguesa' },
  { code: '18', name: 'Sucre' },
  { code: '19', name: 'Táchira' },
  { code: '20', name: 'Trujillo' },
  { code: '21', name: 'Yaracuy' },
  { code: '22', name: 'Zulia' },
  { code: '23', name: 'La Guaira' },
  { code: '24', name: 'Distrito Capital' },
  { code: '25', name: 'Dependencias Federales' },
] as const;
